Various fixes and reimplementation of most of remaining #10 changes
BeeFox-sys/blasebot pull request #11
Opened 2021-04-21 15:50 UTC by estherbolik

This PR includes v2 updates to the README, invite link, and config file, a few miscellaneous bug fixes, and, most notably, the reimplementation of most of the changes from #10 that were not implemented when the PR was closed (I am operating under the assumption that they were accidentally missed rather than intentionally skipped, since some of them were bug fixes). That also includes the reordering of fields on the player card, and while I do believe that it does genuinely improve readability, if you would like me to revert that change (or any of the other purely-formatting ones) I would be happy to do so (since it's somewhat subjective).

Full list of changes:
- Miscellaneous:
  - Update README for v2 (and earlier) changes.
  - Change bot invite link to add `applications.commands` scope, required to use slash commands.
  - Update `sample.config.json` to add `applicationID` (renamed from `clientID`, since the client ID is a separate thing) and remove `prefix`.
  - Replace "/help" with "/info" in the bot's status message, since the former command no longer exists.
  - Fix a couple of typos.
- Game updates:
  - Fix `/i` <-> `/iu` in screenTakeover image URLs.
  - Change Reverb colour from light blue to deep purple (colour-picked from the weather's icon), since the current colour is almost identical to the item damage colour (which does not have a reasonable alternative from the site). [from #10]
- Game cards:
  - Refactor to use `weatherCache` instead of the `Weather` object, delete `Weather` object. [from #10]
  - Refactor to use `emojiString` from `teamUtils`. [from #10]
  - Add team emoji to winner field, to make it more obvious at a glance who the winner is. [from #10]
  - Italicise "Undecided" in upcoming pitcher fields to match formatting in other fields. [from #10]
  - Fix weather being displayed for Season 1 games. [from #10]
- Player cards:
  - Fix tournament-only players being displayed as in Null Team. [from #10]
  - Fix inconsistent formatting for positions in main/tourney teams.
  - Rename several fields to match their names on the site. [from #10]
  - Fix null-checking on coffee and blood, fix missing Espresso text. [from #10]
  - Hide Vibe if player is Scattered and FK is not enabled. [from #10]
  - Fix item adjustment ratings still being displayed even if equal to 0.
  - Revert gilded stars from using combining enclosing circles to using underlines, due to the former unfortunately not being displayed correctly on the Discord desktop app.
  - Fix soulscream formula error. [from #10]
  - Fix game attribute formatting.
  - Reorder fields to better match site. [mostly from #10]
- Team cards:
  - Move Modifications field to be immediately after player lists. [from #10]
  - Add Times Evolved and Runs This Season. [from #10]
  - Fix game attribute formatting.

2021-04-22 23:24 UTC, BeeFox-sys approved these changes

2021-04-27 03:12 UTC, BeeFox-sys requested changes

2021-04-27 03:12 UTC, BeeFox-sys commented on bot/util/playerUtils.js
> +    const team = await getTeam(player.leagueTeamId || player.tournamentTeamId);
should use nullish operator to be safe

2021-04-27 03:12 UTC, BeeFox-sys commented on bot/util/playerUtils.js
> +            ? (player.coffee === 7 ? "Espresso" : await coffeeCache.fetch(player.coffee))
Leave espresso as "coffee?", it is an easteregg to the fact espresso didn't work for a long time

2021-04-27 11:06 UTC, estherbolik commented
Changes implemented :+1:

2021-05-06 08:45 UTC, BeeFox-sys approved these changes

2021-05-10 03:28 UTC, merged